// Auth
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const LOGOUT = 'LOGOUT';

// User
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const GET_CURRENT_USER_FAILURE = 'GET_CURRENT_USER_FAILURE';
export const GET_LIST_USERS_REQUEST = 'GET_LIST_USERS_REQUEST';
export const GET_LIST_USERS_SUCCESS = 'GET_LIST_USERS_SUCCESS';
export const GET_LIST_USERS_FAILURE = 'GET_LIST_USERS_FAILURE';


// Dashboard
export const FETCH_DASHBOARD_STATS_REQUEST = 'FETCH_DASHBOARD_STATS_REQUEST';
export const FETCH_DASHBOARD_STATS_SUCCESS = 'FETCH_DASHBOARD_STATS_SUCCESS';
export const FETCH_DASHBOARD_STATS_FAILURE = 'FETCH_DASHBOARD_STATS_FAILURE';
export const FETCH_DASHBOARD_SALES_REQUEST = 'FETCH_DASHBOARD_SALES_REQUEST';
export const FETCH_DASHBOARD_SALES_SUCCESS = 'FETCH_DASHBOARD_SALES_SUCCESS';
export const FETCH_DASHBOARD_SALES_FAILURE = 'FETCH_DASHBOARD_SALES_FAILURE';
